// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBqcHLKZKmdN80WcCh9-TBvvwXu3fJnGTY',
    appId: '1:149066511053:web:3a0d0a869e5b3695b92f84',
    messagingSenderId: '149066511053',
    projectId: 'flutter-hotel-goin',
    authDomain: 'flutter-hotel-goin.firebaseapp.com',
    storageBucket: 'flutter-hotel-goin.firebasestorage.app',
    measurementId: 'G-933D8NTT0H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAuR5N-f5cG0lko4aWdPLR0yIBoobWQYew',
    appId: '1:149066511053:android:aff4d7532af86f15b92f84',
    messagingSenderId: '149066511053',
    projectId: 'flutter-hotel-goin',
    storageBucket: 'flutter-hotel-goin.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBIwnfKv_FT50i7xjwu5CSgbPjCIRa9Jdg',
    appId: '1:149066511053:ios:9c11ecab5bc0f4a1b92f84',
    messagingSenderId: '149066511053',
    projectId: 'flutter-hotel-goin',
    storageBucket: 'flutter-hotel-goin.firebasestorage.app',
    iosClientId: '149066511053-ehl1auas0ifut2d3lfqro0e4ob8kc0uh.apps.googleusercontent.com',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBIwnfKv_FT50i7xjwu5CSgbPjCIRa9Jdg',
    appId: '1:149066511053:ios:9c11ecab5bc0f4a1b92f84',
    messagingSenderId: '149066511053',
    projectId: 'flutter-hotel-goin',
    storageBucket: 'flutter-hotel-goin.firebasestorage.app',
    iosClientId: '149066511053-ehl1auas0ifut2d3lfqro0e4ob8kc0uh.apps.googleusercontent.com',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBqcHLKZKmdN80WcCh9-TBvvwXu3fJnGTY',
    appId: '1:149066511053:web:92c556cae1018e16b92f84',
    messagingSenderId: '149066511053',
    projectId: 'flutter-hotel-goin',
    authDomain: 'flutter-hotel-goin.firebaseapp.com',
    storageBucket: 'flutter-hotel-goin.firebasestorage.app',
    measurementId: 'G-21HPCEXGRQ',
  );
}
